spring.application.name=btg-investment-funds-ms
server.servlet.context-path=/btg-investment-funds/api/v1
server.port=${PORT:8080}
# Conexion a MongoDB Atlas
spring.data.mongodb.uri=${MONGODB_URI}

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG